/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "../Inc/Gpio.hpp"
#include "../Inc/Button.hpp"
#include "../Inc/Timer.hpp"
#include "../Inc/Uart.hpp"
#include "../Inc/Config.hpp"
#include <stdio.h>
#include <cstring>
//drivers/cmsis/include/core_cm0plus////systick_config - method
//To Cortex system timer - in hal clock config

//USART2_TX - PA2
//USART2_RX - PA3

int main(void)
{
	SystemTimer::Init(4000);

	GpioOutput<GPIOA_BASE, 5> ld2;
	UART2 uart2;

	while (true)
	{
		if (uart2.GetString() == ERROR_CODE::OK)
			uart2.SendString(uart2.GetBuffer());

		if (strcmp(uart2.GetBuffer(), "set") == 0)
			ld2.Set();
		else if (strcmp(uart2.GetBuffer(), "clear") == 0)
			ld2.Clear();
		else if (strcmp(uart2.GetBuffer(), "toggle") == 0)
			ld2.Toggle();
	}
}


